# Generated by Django 5.1.3 on 2024-11-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The last time this record was updated.')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('season', models.CharField(max_length=8, verbose_name='Event Season')),
                ('event_start_date', models.DateTimeField()),
                ('event_end_date', models.DateTimeField()),
                ('registration_start_date', models.DateTimeField()),
                ('registration_end_date', models.DateTimeField()),
                ('location', models.CharField(default='', max_length=500)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed')], default='upcoming', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
