# Generated by Django 5.1.4 on 2025-02-07 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksu_events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_organizer',
        ),
        migrations.AddField(
            model_name='user',
            name='auth_role'
        ),
        migrations.AddField(
            model_name='user',
            name='event',
            field=models.ForeignKey(default='ORG', on_delete=django.db.models.deletion.CASCADE, to='ksu_events.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
