# Generated by Django 5.1.4 on 2025-02-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksu_events', '0002_remove_user_is_organizer_user_auth_role_user_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_role',
            field=models.CharField(choices=[('ORG', 'Organizer'), ('VOL', 'Volunteer'), ('PAR', 'Participant')], default='ORG', max_length=3),
        ),
    ]
