# Generated by Django 5.1.4 on 2025-02-14 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksu_events', '0003_alter_user_auth_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ksu_events.event'),
        ),
    ]
