# Generated by Django 5.1.6 on 2025-02-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksu_events', '0004_alter_user_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The last time this record was updated.')),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='registration_end_date',
            new_name='registration_end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_start_date',
            new_name='registration_start',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='registration_start_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='auth_role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='event',
        ),
        migrations.RemoveField(
            model_name='user',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
    ]
