# Generated by Django 5.1.6 on 2025-02-24 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksu_events', '0005_eventattendance_rename_event_end_date_event_end_date_and_more'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendance',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registrations'),
        ),
        migrations.AlterUniqueTogether(
            name='eventattendance',
            unique_together={('registration', 'created_at')},
        ),
    ]
