# Generated by Django 5.1.6 on 2025-02-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksu_events', '0006_eventattendance_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_role',
            field=models.CharField(choices=[('ORG', 'Organizer'), ('VOL', 'Volunteer'), ('PAR', 'Participant')], default='ORG', max_length=3),
        ),
    ]
