# Generated by Django 5.1.6 on 2025-02-24 16:47

import django.db.models.deletion
import django_countries.fields
import ksu_events.registration.formatChecker
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ksu_events', '0005_eventattendance_rename_event_end_date_event_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EthnicityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=4)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MajorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=4)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalRegistrations',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='The time this record was created.')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='The last time this record was updated.')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('dietary_restrictions', models.TextField(blank=True, default='', max_length=250, null=True, verbose_name='Do you have any dietary restrictions?')),
                ('phone_number', models.CharField(max_length=15)),
                ('is_minor', models.BooleanField(default=False, verbose_name='Under 18')),
                ('participation', models.CharField(choices=[('N/A', 'Not Sure'), ('ONL', 'Online'), ('INP', 'In-person')], default='INP', max_length=4, verbose_name='How do you plan to participate in this event?')),
                ('shirt_size', models.CharField(choices=[('EXS', 'X-Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'X-Large'), ('XXL', 'XX-Large')], max_length=4, verbose_name='Shirt Size')),
                ('year_in_school', models.CharField(choices=[('HSFR', 'High School Freshman'), ('HSSO', 'High School Sophomore'), ('HSJR', 'High School Junior'), ('HSSR', 'High School Senior'), ('CFR', 'College Freshman'), ('CSO', 'College Sophomore'), ('CJR', 'College Junior'), ('CSR', 'College Senior'), ('COLD', 'College 5th year or greater'), ('NTRD', 'Nontraditional Student'), ('GRDS', 'Graduate Student'), ('VOCA', 'Other Vocational / Trade Program or Apprenticeship'), ('NO', 'I prefer not to answer')], max_length=4, verbose_name='Education Level')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ksu_events.event')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical registrations',
                'verbose_name_plural': 'historical registrationss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The last time this record was updated.')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('dietary_restrictions', models.TextField(blank=True, default='', max_length=250, null=True, verbose_name='Do you have any dietary restrictions?')),
                ('phone_number', models.CharField(max_length=15)),
                ('is_minor', models.BooleanField(default=False, verbose_name='Under 18')),
                ('participation', models.CharField(choices=[('N/A', 'Not Sure'), ('ONL', 'Online'), ('INP', 'In-person')], default='INP', max_length=4, verbose_name='How do you plan to participate in this event?')),
                ('shirt_size', models.CharField(choices=[('EXS', 'X-Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'X-Large'), ('XXL', 'XX-Large')], max_length=4, verbose_name='Shirt Size')),
                ('year_in_school', models.CharField(choices=[('HSFR', 'High School Freshman'), ('HSSO', 'High School Sophomore'), ('HSJR', 'High School Junior'), ('HSSR', 'High School Senior'), ('CFR', 'College Freshman'), ('CSO', 'College Sophomore'), ('CJR', 'College Junior'), ('CSR', 'College Senior'), ('COLD', 'College 5th year or greater'), ('NTRD', 'Nontraditional Student'), ('GRDS', 'Graduate Student'), ('VOCA', 'Other Vocational / Trade Program or Apprenticeship'), ('NO', 'I prefer not to answer')], max_length=4, verbose_name='Education Level')),
                ('ethnicity', models.ManyToManyField(to='registration.ethnicityoption')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ksu_events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The last time this record was updated.')),
                ('qWhy', models.TextField(default='', max_length=1000, verbose_name='Why do you want to participate in this event?')),
                ('qExpectations', models.TextField(default='', max_length=1000, verbose_name='What do you hope to get out of this event?')),
                ('qPrize', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Any cool prizes you would like to win? Share them here!')),
                ('resume', ksu_events.registration.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='resume/')),
                ('school', models.CharField(default='', max_length=100)),
                ('major', models.ManyToManyField(to='registration.majoroption')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registration.registrations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chaperone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The last time this record was updated.')),
                ('affiliation', models.CharField(max_length=255, verbose_name='Affiliation')),
                ('profession', models.CharField(max_length=255, verbose_name='Profession')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('registration_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registration.registrations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipantChaperone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The last time this record was updated.')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('chaperone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaperoned_participants', to='registration.chaperone', verbose_name='Chaperone')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_chaperone', to=settings.AUTH_USER_MODEL, verbose_name='Participant')),
            ],
            options={
                'unique_together': {('participant', 'chaperone')},
            },
        ),
        migrations.AddConstraint(
            model_name='registrations',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='cnst_unique_userEvent'),
        ),
    ]
