# Generated by Django 5.1.6 on 2025-04-11 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendance',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registrations'),
        ),
        migrations.AddField(
            model_name='subevent',
            name='parent_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.event'),
        ),
        migrations.AlterUniqueTogether(
            name='eventattendance',
            unique_together={('registration', 'created_at')},
        ),
        migrations.AlterUniqueTogether(
            name='subevent',
            unique_together={('subevent_name', 'parent_event')},
        ),
    ]
